POST http://127.0.0.1:8000/process HTTP/1.1
content-type: application/json

{
  "urls": [
    "https://picsum.photos/200",
    "https://picsum.photos/201",
    "https://picsum.photos/202",
    "https://picsum.photos/203",
    "https://picsum.photos/204",
    "https://picsum.photos/205",
    "https://picsum.photos/206",
    "https://picsum.photos/207",
    "https://picsum.photos/208",
    "https://picsum.photos/209",
    "https://picsum.photos/210",
    "https://picsum.photos/211",
    "https://picsum.photos/212",
    "https://picsum.photos/213",
    "https://picsum.photos/214",
    "https://picsum.photos/215",
    "https://picsum.photos/216",
    "https://picsum.photos/217",
    "https://picsum.photos/218",
    "https://picsum.photos/219",
    "https://picsum.photos/220",
    "https://picsum.photos/221",
    "https://picsum.photos/222",
    "https://picsum.photos/223",
    "https://picsum.photos/224",
    "https://picsum.photos/225",
    "https://picsum.photos/226",
    "https://picsum.photos/227",
    "https://picsum.photos/228",
    "https://picsum.photos/229",
    "https://picsum.photos/230",
    "https://picsum.photos/231",
    "https://picsum.photos/232",
    "https://picsum.photos/233",
    "https://picsum.photos/234",
    "https://picsum.photos/235",
    "https://picsum.photos/236",
    "https://picsum.photos/237",
    "https://picsum.photos/238",
    "https://picsum.photos/239",
    "https://picsum.photos/240",
    "https://picsum.photos/241",
    "https://picsum.photos/242",
    "https://picsum.photos/243",
    "https://picsum.photos/244",
    "https://picsum.photos/245",
    "https://picsum.photos/246",
    "https://picsum.photos/247",
    "https://picsum.photos/248",
    "https://picsum.photos/249",
    "https://picsum.photos/200",
    "https://picsum.photos/201",
    "https://picsum.photos/202",
    "https://picsum.photos/203",
    "https://picsum.photos/204",
    "https://picsum.photos/205",
    "https://picsum.photos/206",
    "https://picsum.photos/207",
    "https://picsum.photos/208",
    "https://picsum.photos/209",
    "https://picsum.photos/210",
    "https://picsum.photos/211",
    "https://picsum.photos/212",
    "https://picsum.photos/213",
    "https://picsum.photos/214",
    "https://picsum.photos/215",
    "https://picsum.photos/216",
    "https://picsum.photos/217",
    "https://picsum.photos/218",
    "https://picsum.photos/219",
    "https://picsum.photos/220",
    "https://picsum.photos/221",
    "https://picsum.photos/222",
    "https://picsum.photos/223",
    "https://picsum.photos/224",
    "https://picsum.photos/225",
    "https://picsum.photos/226",
    "https://picsum.photos/227",
    "https://picsum.photos/228",
    "https://picsum.photos/229",
    "https://picsum.photos/230",
    "https://picsum.photos/231",
    "https://picsum.photos/232",
    "https://picsum.photos/233",
    "https://picsum.photos/234",
    "https://picsum.photos/235",
    "https://picsum.photos/236",
    "https://picsum.photos/237",
    "https://picsum.photos/238",
    "https://picsum.photos/239",
    "https://picsum.photos/240",
    "https://picsum.photos/241",
    "https://picsum.photos/242",
    "https://picsum.photos/243",
    "https://picsum.photos/244",
    "https://picsum.photos/245",
    "https://picsum.photos/246",
    "https://picsum.photos/247",
    "https://picsum.photos/248",
    "https://picsum.photos/249"
      ],
  "workers": {
    "descarga": 8,
    "redimension": 4,
    "formato": 4,
    "marca_agua": 4
  }
}

###
GET  http://127.0.0.1:8000/process/aded9555-687f-427d-9970-a0e6079b78d6 HTTP/1.1