POST http://127.0.0.1:8000/process HTTP/1.1
content-type: application/json

{
  "urls": [
    "https://imgs.search.brave.com/YkejnsF1EknXiEXdyLj_1cCYXwrd_cJd5_yS-2b0vLU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/bW9ieWdhbWVzLmNv/bS8wMjczM2ExNi1h/YzBkLTExZWQtOTJj/Yi0wMjQyMGEwMDAx/MzIud2VicA",
    "https://imgs.search.brave.com/BW0zo4Dr1fLVwa3999XTcCmXLLklK_4o2SHNrC7unr8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9yYW5k/b21vdXRwdXRzLmNv/bS9hc3NldHMvaW1h/Z2VzL3RodW1ibmFp/bHMvNDI4eDMwMC9y/YW5kb20tdmlkZW8t/Z2FtZS1nZW5lcmF0/b3Iud2VicA",
    "https://imgs.search.brave.com/s3Hmgi6dlBudbGnB-AKEU-1iaUO0RuHZFQdQJWSYW1U/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hLnRo/dW1icy5yZWRkaXRt/ZWRpYS5jb20vVS0z/OWQzMkdBZWVrRG1h/c2xCazRjcXVDZjVX/dHFFMjRSYzg0VXJX/akdTOC5qcGc",
    "https://imgs.search.brave.com/TeOyTeGbRKIxQ03NErc0Cp9O89P_fVBFJcHS814CmOg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Yml0bWFwYm9va3Mu/Y29tL2Nkbi9zaG9w/L3Byb2R1Y3RzL0JO/VF8wNzBfMTMxOHg4/NzkuanBnP3Y9MTY2/MTQ1Nzg0Mw"
  ],
  "workers": {
    "descarga": 4,
    "redimension": 2,
    "formato": 2,
    "marca_agua": 2
  }
}

###
GET  http://127.0.0.1:8000/process/18cc6463-abdd-4e39-ac26-2d3495a97a07 HTTP/1.1